"""Initial migration with Flask-Migrate

Revision ID: a12af7e857f9
Revises: 
Create Date: 2025-08-07 13:40:00.024602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12af7e857f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('profile_name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('weekly_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('food_id', sa.String(), nullable=False),
    sa.Column('food_name', sa.String(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_name'], ['profiles.profile_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id')
    )
    with op.batch_alter_table('weekly_log', schema=None) as batch_op:
        batch_op.create_index('idx_profile_date', ['profile_name', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_log_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_log_date'))
        batch_op.drop_index('idx_profile_date')

    op.drop_table('weekly_log')
    op.drop_table('profiles')
    # ### end Alembic commands ###
